var platformSheets = [];
var platforms = [];
var underworldPlatforms = [];   
var decorativePlatforms = [];
var UdecorativePlatforms = [];
var signs = [];
function loadPlatforms(AM) {
    platformSheets['barrel'] = AM.getAsset("./assets/platforms/Volcano Level Set_Platformer - Wooden Barrel.png");
    platformSheets['sandTop'] = AM.getAsset("./assets/platforms/DesertPlatforms/tiles/01.png");
    platformSheets['sandMid'] = AM.getAsset("./assets/platforms/DesertPlatforms/tiles/02.png");
    platformSheets['gap1'] = AM.getAsset("./assets/platforms/PNG/Platformer/Gap1.png");
    platformSheets['side left 2'] = AM.getAsset("./assets/platforms/PNG/Platformer/Side Left 2.png");
    platformSheets['side left'] = AM.getAsset("./assets/platforms/PNG/Platformer/Side Left.png");
    platformSheets['side right'] = AM.getAsset("./assets/platforms/PNG/Platformer/Side Right.png");
    platformSheets['side right 2'] = AM.getAsset("./assets/platforms/PNG/Platformer/Side Right 2.png");
    platformSheets['square ground'] = AM.getAsset("./assets/platforms/PNG/Platformer/Square Ground.png");
    platformSheets['arrow 1'] = AM.getAsset("./assets/platforms/PNG/Environment/Arrow1.png");
    platformSheets['arrow 2'] = AM.getAsset("./assets/platforms/PNG/Environment/Arrow2.png");
    platformSheets['arrow 3'] = AM.getAsset("./assets/platforms/PNG/Environment/Arrow3.png");
    platformSheets['caution'] = AM.getAsset("./assets/platforms/PNG/Environment/Caution.png");
    platformSheets['question'] = AM.getAsset("./assets/platforms/PNG/Environment/Question.png");
    platformSheets['skull'] = AM.getAsset("./assets/platforms/PNG/Environment/Skull.png");
    platformSheets['brickTop'] = AM.getAsset("./assets/platforms/temple/tiles/01.png");
    platformSheets['brickMid'] = AM.getAsset("./assets/platforms/temple/tiles/02.png");
    platformSheets['brickChisled'] = AM.getAsset("./assets/platforms/temple/tiles/03.png");
    platformSheets['block'] = AM.getAsset("./assets/platforms/temple/tiles/breakable.png");
    platformSheets['pedestal'] = AM.getAsset("./assets/platforms/temple/tiles/pedestal.png");
    platformSheets['bridge-2'] = AM.getAsset("./assets/platforms/temple/tiles/bridge-2.png");
    platformSheets['bridge-3'] = AM.getAsset("./assets/platforms/temple/tiles/bridge-3.png");
    
    platformSheets['stoneMid'] = AM.getAsset("./assets/platforms/volcanoTiles/tiles/02.png");
    platformSheets['stoneTop'] = AM.getAsset("./assets/platforms/volcanoTiles/tiles/01.png");
    platformSheets['spikes'] = AM.getAsset("./assets/platforms/PNG/Platformer/Spikes.png");
    platformSheets['silver chest'] = AM.getAsset("./assets/platforms/PNG/Collectable/Treasure Chest.png");
    platformSheets['red flag'] = AM.getAsset("./assets/platforms/PNG/Environment/Red Flag.png");

}

function PlatformController (game, assetManager) {
    this.AM = assetManager;
    loadPlatforms(this.AM);
    this.engine = game;
    this.ctx = game.ctx;
}

// PlatformController.prototype = new Entity();
PlatformController.prototype.constructor = PlatformController;

PlatformController.prototype.loadPlatformsLevel1 = function () {
    


        // removePlatforms();
        //page 1
        decorativePlatforms.push(new Platform(this.engine, platformSheets['arrow 1'], -2, 7,));
        signs.push(new hint(this.engine, platformSheets['question'], 0, 7, false, "wrong way!"));
        //platforms.push(new Platform(this.engine, platformSheets['side left 2'], 6, 7, true));
        signs.push(new hint(this.engine, platformSheets['question'], 7, 7, false, "up arrow to jump"));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 8, 7, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 9, 7, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 10, 7, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 15, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 15, 6, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 19, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 19, 6, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 19, 5, true, false, false));
        signs.push(new hint(this.engine, platformSheets['question'], 21, 7, false, "try pushing space"));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 23, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 23, 6, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 23, 5, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 23, 4, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 23, 3, true, false, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],8, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],9, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],10, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],15, 7, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],15, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],19, 7, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],19, 6, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],19, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],23, 4, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],23, 3, true, true, false));
        signs.push(new hint(this.engine, platformSheets['question'], 27, 7, false, "use 'e' to attack"));
        decorativePlatforms.push(new Platform(this.engine, platformSheets['caution'], 29, 7, true));
        UdecorativePlatforms.push(new Platform(this.engine, platformSheets['caution'], 29, 7, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],30, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],31, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],32, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],33, 6, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],33, 7, true, true, false));
        
        //page 2
        //platforms.push(new Platform(this.engine, platformSheets['spikes'], 39, 7, true, false, true));
        //platforms.push(new Platform(this.engine, platformSheets['spikes'], 40, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 41, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 42, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 43, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 44, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 45, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 46, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 47, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 48, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 49, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 50, 7, true, false, true));
        //platforms.push(new Platform(this.engine, platformSheets['spikes'], 51, 7, true, false, true));
        //platforms.push(new Platform(this.engine, platformSheets['spikes'], 52, 7, true, false, true));
        signs.push(new hint(this.engine, platformSheets['question'], 55, 7, false, "use 'q' to throw"));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 40, 6, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 41, 6, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 44, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 45, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 46, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 59, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 59, 6, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 59, 5, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 59, 4, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandMid'], 59, 3, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['sandTop'], 59, 2, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 66, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 66, 6, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 67, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 68, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 69, 7, false, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 69, 6, false, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 69, 5, false, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 69, 4, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 70, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 71, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 72, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 72, 6, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 72, 5, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 72, 4, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 72, 3, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 72, 2, true, false, false));
        
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],39, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],40, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],41, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],42, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],43, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],44, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],45, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],46, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],47, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],48, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],49, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],50, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],51, 7, true, true, true));
        //underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],52, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],40, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],41, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],44, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],45, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],46, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],47, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],48, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],49, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],50, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],51, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],59, 7, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],59, 6, true, true, false));
        UdecorativePlatforms.push(new Platform(this.engine, platformSheets['stoneMid'],59, 3, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],59, 2, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],66, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],67, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],68, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],69, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],70, 7, true, true, true));
        //underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'],71, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],72, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 75, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 76, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 77, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 78, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 79, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 80, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 81, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 82, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 83, 7, false, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 75, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 76, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 77, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 78, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 79, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 80, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 81, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 82, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 83, 6, true, true, false));
        
        // //page 3
        //these following spikes kill the pharaoh in the underworld even though they belong to the overworld
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 75, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 76, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 77, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 78, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 79, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 80, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 81, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 82, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 83, 7, true, false, true));      
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 87, 5, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 87, 4, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 87, 3, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 87, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickMid'], 90, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickMid'], 91, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickMid'], 92, 5, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 90, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 91, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 92, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 93, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 94, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 95, 2, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 95, 7, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 95, 6, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 95, 5, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 95, 4, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickChisled'], 95, 3, false, false, false));
        platforms.push(new Platform(this.engine, platformSheets['barrel'], 93, 7, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['barrel'], 94, 7, true, false, false));
        decorativePlatforms.push(new Platform(this.engine, platformSheets['bridge-3'], 87, 7, true, false, false));
        decorativePlatforms.push(new Platform(this.engine, platformSheets['bridge-2'], 87, 6, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 96, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 97, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 98, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 99, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 100, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 101, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 102, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 103, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 104, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 105, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 106, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 107, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['spikes'], 108, 7, true, false, true));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 98, 4, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 99, 4, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 100, 4, true, false, false));
        platforms.push(new Platform(this.engine, platformSheets['brickTop'], 101, 4, true, false, false));

        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 88, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 89, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 90, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 91, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 92, 5, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 90, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 91, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 92, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 93, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 94, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 95, 2, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 95, 7, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 95, 6, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 95, 5, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 95, 4, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 95, 3, false, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['pedestal'], 94, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['pedestal'], 87, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneMid'], 87, 5, false, true, false));
        UdecorativePlatforms.push(new Platform(this.engine, platformSheets['bridge-2'], 87, 6, true, true, false));
        UdecorativePlatforms.push(new Platform(this.engine, platformSheets['bridge-3'], 87, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['block'], 91, 7, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['block'], 91, 6, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['block'], 91, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['block'], 91, 3, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 96, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 97, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 98, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 99, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 100, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 101, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 102, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 103, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 104, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 105, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 106, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 107, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['spikes'], 108, 7, true, true, true));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 102, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 103, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 104, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 105, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 106, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 107, 4, true, true, false));
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'], 108, 4, true, true, false));
   
        underworldPlatforms.push(new Platform(this.engine, platformSheets['stoneTop'],33, 7, true, true, false));

        decorativePlatforms.push(new Platform(this.engine, platformSheets['silver chest'], 107.1, 3.1, true, true, false));
        decorativePlatforms.push(new Platform(this.engine, platformSheets['barrel'], 108, 3.1, true, true, false));
        decorativePlatforms.push(new Platform(this.engine, platformSheets['red flag'], 108.3, 2.2, true, true, false));

        // } else {
    //     // removePlatforms();
    //     platforms.splice(0, platforms.length);
    // }
}